---
- hosts: all
  remote_user: wal
  vars:
    program: "pixel_ngxlua"
    luarocks: "/usr/local/openresty/luajit/bin/luarocks"
    app: "/home/wal/pixel_ngxlua"
    bin: "{{ app }}/bin"

  tasks:
    - name: ensure that needed luarocks are installed
      sudo: yes
      shell: "{{ luarocks }} install {{ item }}"
      with_items:
        - lua-inih
        - lua-cjson
        - lua-cmsgpack
        - lua_cliargs
        - luacrypto
        - luasocket
        - lzmq
        - redis-lua
        - serpent
        - sha1
        - statsd
      tags:
        - rocks

    - name: copy ini and lua files to bin directory
      copy: src=src/{{ item }} dest={{ bin }}/
      with_items:
        - cstream.ini
        - cstream_pub.lua
        - cstream_sub.lua
        - ml.lua
        - print_clicks.lua
        - rutarget.lua
        - storage.lua
        - zhelpers.lua
      tags:
        - scripts

    - name: ensure right mode on cstream utilities
      file: name={{ bin }}/{{ item }} mode=0755
      with_items:
        - cstream_pub.lua
        - cstream_sub.lua
        - print_clicks.lua
      tags:
        - scripts

    - name: copy supervisor config file for cstream_sub
      sudo: yes
      copy: src=cstream_sub.conf dest=/etc/supervisor/conf.d/cstream.conf
      tags:
        - supervisor

    - name: restart supervisor
      sudo: yes
      service: name=supervisor state=restarted
      tags:
        - supervisor
